required_fields = {'0.1': {'statementID': (True, str),
                           'statementType': (True, str),
                           'statementType==': {'personStatement': {'personType': (True, str)},
                                               'entityStatement': {'entityType': (True, str)},
                                               'ownershipOrControlStatement': {'subject': (True, {'describedByEntityStatement': (True, str)}),
                                                                               'interestedParty': (True, {'unspecified': (False, {'reason': (True, str)})})}}},
                   '0.2': {'statementID': (True, str),
                           'statementType': (True, str),
                           'publicationDetails': (True, {'publicationDate': (True, str), 'bodsVersion': (True, str)}),
                           'isComponent': (True, bool),
                           'statementType==': {'personStatement': {'personType': (True, str),
                                                                   'unspecifiedPersonDetails': (False, {'reason': (True, str)})},
                                               'entityStatement': {'entityType': (True, str),
                                                                   'unspecifiedEntityDetails': (False, {'reason': (True, str)})},
                                               'ownershipOrControlStatement': {'subject': (True, {'describedByEntityStatement': (True, str)}),
                                                                               'interestedParty': (True, {'unspecified': (False, {'reason': (True, str)})})}}},
                   '0.3': {'statementID': (True, str),
                           'statementType': (True, str),
                           'publicationDetails': (True, {'publicationDate': (True, str), 'bodsVersion': (True, str), 'publisher': (True, dict)}),
                           'isComponent': (True, bool),
                           'statementType==': {'personStatement': {'personType': (True, str),
                                                                   'unspecifiedPersonDetails': (False, {'reason': (True, str)})},
                                               'entityStatement': {'entityType': (True, str),
                                                                   'unspecifiedEntityDetails': (False, {'reason': (True, str)})},
                                               'ownershipOrControlStatement': {'subject': (True, {'describedByEntityStatement': (True, str)}),
                                                                               'interestedParty': (True, {'unspecified': (False, {'reason': (True, str)})})}}}
                  }
